pages:
  image: maven:3.9-eclipse-temurin-21
  stage: deploy
  script:
    - mvn javadoc:javadoc -q
    - mkdir -p public
    - cp -r docs/apidocs/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
