image: maven:3.9.6-eclipse-temurin-21

stages:
  - pages

pages:
  stage: pages
  script:
    - mvn clean package javadoc:javadoc
    - mkdir public
    - cp -r target/site/apidocs/* public/
  artifacts:
    paths:
      - public
  only:
    - main